const colors = require('tailwindcss/colors')

module.exports = {
  ...colors,

  // todo: with the following code you can use element colors
  primary: 'var(--el-color-primary)',
  success: 'var(--el-color-success)',
  warning: 'var(--el-color-warning)',
  danger: 'var(--el-color-danger)',

  transparent: 'transparent',
  current: 'currentColor',
  black: '#000',
  white: '#fff',
  dark: '#1F1F1F',
  alto: '#D9D9D9',
  silver: '#C4C4C4',
  // TODO: fix duplicate hex colors
  // primary: '#146DF6',
  // success: '#28AA35',
  // ---------
  selago: '#F4F8FE',
  kimberly: '#6E6893',
  snuff: '#D9D5EC',
  scorpion: '#5E5D5D',
  gray: '#6b7280',
  'gray-light': '#f3f4f6',
  'gray-ultra-light': '#e5e7eb',
  'gray-medium': '#9ca3af',
  'gray-dark': '#374151',
  'catskill-white': '#F5F7FA',
  'lavender-purple': '#8B83BA'
  // accent: '#F2F8FF',
  // denim: '#1256BF',
  // calypso: '#37658A',
  // danube: '#599CD2',
  // gray: '#878787',
  // tangaroa: '#071B2B',
  // concrete: '#F3F3F3',
  // astronaut: '#255072',
  // mandy: '#E3507A',
  // gallery: '#EAEAEA',
  // platinum: '#E4E4E4',
  // zircon: '#F4F9FF',
  // 'red-primary': '#F56C6C',
  // 'persian-red': '#C92F2F',
  // 'cloudy-blue': '#b7bed8',
  // 'very-light-blue': '#e6efff',
  // 'burnt-sienna': '#EF6E5D',
  // 'white-lilac': '#F2F0F9',
  // 'twilight-blue': '#FEFFFF',
  // 'link-water': '#e7f1f8',
  // 'hawkes-blue': '#DCE9FE',
  // 'boston-blue': '#3F8CCA',
  // 'blue-whale': '#042C42',
  // 'big-stone': '#12273B',
  // 'dusty-gray': '#979797',
  // 'mine-shaft': '#1F1F1F',
  // 'dove-gray': '#706E6E',
  // 'royal-blue': '#3282ED',
  // 'cape-cod': '#3E4042',
  // 'oslo-gray': '#868B90',
  // 'steel-gray': '#25213B',
  // 'granite-gray': '#676767',
  // 'chinese-yellow': '#FEAF01',
  // 'philippine-silver': '#B6B6B6',
  // 'rich-black': '#020325',
  // 'yankees-blue': '#181b3e',
  // 'bazzled-blue': '#0c142a',
  // 'bazzled-blue-light': '#34588A',
  // 'chinese-white': '#E0E0E0',
  // 'bright-gray': '#ECECEC'
}
